// original outdated map with old db names
export const TEAM_MAP = new Map<string, string>([
  ["Arsenal FC", "Arsenal"],
  ["Aston Villa FC", "Aston Villa"],
  ["Barnsley FC", "Barnsley"],
  ["Birmingham City FC", "Birmingham"],
  ["Blackburn Rovers FC", "Blackburn Rovers"],
  ["Blackpool FC", "Blackpool"],
  ["Bolton Wanderers FC", "Bolton"],
  ["Brentford FC", "Brentford"],
  ["AFC Bournemouth", "Bournemouth"],
  ["Bradford City AFC", "Bradford City"],
  ["Brighton & Hove Albion FC", "Brighton"],
  ["Bristol City FC", "Bristol City"],
  ["Burnley FC", "Burnley"],
  ["Cardiff City FC", "Cardiff City"],
  ["Charlton Athletic FC", "Charlton"],
  ["Chelsea FC", "Chelsea"],
  ["Coventry City FC", "Coventry"],
  ["Crystal Palace FC", "Crystal Palace"],
  ["Derby County FC", "Derby County"],
  ["Everton FC", "Everton"],
  ["Fulham FC", "Fulham"],
  ["Huddersfield Town AFC", "Huddersfield"],
  ["Hull City AFC", "Hull City"],
  ["Ipswich Town FC", "Ipswich Town"],
  ["Leeds United FC", "Leeds United"],
  ["Leicester City FC", "Leicester"],
  ["Liverpool FC", "Liverpool"],
  ["Luton Town FC", "Luton Town"],
  ["Manchester City FC", "Man City"],
  ["Manchester United FC", "Man United"],
  ["Middlesbrough FC", "Middlesbrough"],
  ["Millwall FC", "Millwall"],
  ["Newcastle United FC", "Newcastle"],
  ["Norwich City FC", "Norwich City"],
  ["Nottingham Forest FC", "Nott'm Forest"],
  ["Oldham Athletic AFC", "Oldham Athletic"],
  ["Plymouth Argyle FC", "Plymouth"],
  ["Portsmouth FC", "Portsmouth"],
  ["Preston North End FC", "Preston"],
  ["Queens Park Rangers FC", "QPR"],
  ["Reading FC", "Reading"],
  ["Rotherham United FC", "Rotherham"],
  ["Sheffield United FC", "Sheffield United"],
  ["Sheffield Wednesday FC", "Sheffield Wednesday"],
  ["Southampton FC", "Southampton"],
  ["Stoke City FC", "Stoke City"],
  ["Sunderland AFC", "Sunderland"],
  ["Swansea City AFC", "Swansea"],
  ["Swindon Town AFC", "Swindon Town"],
  ["Tottenham Hotspur FC", "Tottenham"],
  ["Watford FC", "Watford"],
  ["West Bromwich Albion FC", "West Brom"],
  ["West Ham United FC", "West Ham"],
  ["Wigan Athletic FC", "Wigan Athletic"],
  ["Wimbledon FC", "Wimbledon"],
  ["Wolverhampton Wanderers FC", "Wolves"],
]);

// may have been for reducing the size to fix overflow issues
export const UNDERSTAT_MAP = new Map<string, string>([
  ["Newcastle", "Newcastle United"],
  ["Man City", "Manchester City"],
  ["Man United", "Manchester United"],
  ["Wolves", "Wolverhampton Wanderers"],
  ["Nottm Forest", "Nottingham Forest"],
]);

// this normalizes team standings - not necessary anymore since I use my own algo
export const standings_map = new Map<string, string>([
  ["Brighton Hove", "Brighton"],
  ["Nottingham", "Nott'm Forest"],
  ["Wolverhampton", "Wolves"],
  ["Bayern", "Bayern Munich"],
  ["Stuttgart", "VfB Stuttgart"],
  ["1. FC Köln", "FC Koln"],
  ["Frankfurt", "Eintracht Frankfurt"],
  ["Freiburg", "SC Freiburg"],
  ["HSV", "Hamburger SV"],
  ["St. Pauli", "St Pauli"],
  ["Bremen", "Werder Bremen"],
  ["Olympique Lyon", "Lyon"],
  ["RC Lens", "Lens"],
  ["Stade Rennais", "Rennes"],
  ["Angers SCO", "Angers"],
  ["FC Metz", "Metz"],
  ["Como 1907", "Como"],
  ["AC Pisa", "Pisa"],
  ["Barça", "Barcelona"],
  ["Atleti", "Atletico Madrid"],
  ["Sevilla FC", "Sevilla"],
  ["Athletic", "Athletic Club"],
  ["Alavés", "Alaves"],
  ["Celta", "Celta Vigo"],
  ["Real Oviedo", "Oviedo"],
  ["Leganés", "Leganes"],
  ["Sheffield Utd", "Sheffield United"],
  ["Cádiz CF", "Cadiz"],
  ["Almería", "Almeria"],
  ["Ipswich", "Ipswich Town"],
]);

// this normalizes the-odds-api team names
export const ODDS_MAP = new Map<string, string>([
  // Premier League
  ["Newcastle United", "Newcastle"],
  ["Tottenham Hotspur", "Tottenham"],
  ["Manchester United", "Man United"],
  ["Manchester City", "Man City"],
  ["Wolverhampton Wanderers", "Wolves"],
  ["Brighton and Hove Albion", "Brighton"],
  ["Nottingham Forest", "Nott'm Forest"],
  ["West Ham United", "West Ham"],
  // La Liga
  ["CA Osasuna", "Osasuna"],
  ["Atlético Madrid", "Atletico Madrid"],
  ["Alavés", "Alaves"],
  ["Athletic Bilbao", "Athletic Club"],
  ["Elche CF", "Elche"],
  // Ligue 1
  ["Paris Saint Germain", "PSG"],
  ["AS Monaco", "Monaco"],
  ["RC Lens", "Lens"],
  // Serie A
  ["AC Milan", "Milan"],
  ["AS Roma", "Roma"],
  ["Atalanta BC", "Atalanta"],
  ["Inter Milan", "Inter"],
  ["Hellas Verona", "Verona"],
  // Bundesliga
  ["FC St. Pauli", "St Pauli"],
  ["TSG Hoffenheim", "Hoffenheim"],
  ["1. FC Heidenheim", "Heidenheim"],
  ["FSV Mainz 05", "Mainz"],
  ["Borussia Monchengladbach", "M'gladbach"],
  ["1. FC Köln", "FC Koln"],
  ["Borussia Dortmund", "Dortmund"],
  ["VfL Wolfsburg", "Wolfsburg"],
  ["Bayer Leverkusen", "Leverkusen"],
]);

// normalizes the names of teams from the football-data.co.uk match stats csv files.
export const exception_teams = new Map<string, string>([
  // La Liga
  ["Ath Bilbao", "Athletic Club"],
  ["Sociedad", "Real Sociedad"],
  ["Celta", "Celta Vigo"],
  ["Betis", "Real Betis"],
  ["Vallecano", "Rayo Vallecano"],
  ["La Coruna", "Deportivo"],
  ["Ath Madrid", "Atletico Madrid"],
  ["Espanol", "Espanyol"],
  ["Santander", "Racing"],
  // Bundesliga
  ["Stuttgart", "VfB Stuttgart"],
  ["Freiburg", "SC Freiburg"],
  ["Bochum", "VfL Bochum"],
  ["Ein Frankfurt", "Eintracht Frankfurt"],
  ["Hamburg", "Hamburger SV"],
  ["Braunschweig", "Eintracht Braunschweig"],
  // Serie A
  ["Carpi", "Athletic Carpi"],
  // Ligue 1
  ["Paris SG", "PSG"],
  ["Amiens", "Amiens SC"],
  ["St Etienne", "St-Etienne"],
  ["Evian Thonon Gaillard", "Thonon Evian"],
  // Premier League
  ["Ipswich", "Ipswich Town"],
  ["Leicester", "Leicester City"],
  ["Leeds", "Leeds United"],
  ["Luton", "Luton Town"],
  ["Blackburn", "Blackburn Rovers"],
  ["Wigan", "Wigan Athletic"],
]);

// team ids for football-data api, used for fetching squads through team api
export const team_to_id = new Map<string, number>([
  // Premier League
  ["Arsenal", 57],
  ["Bournemouth", 1044],
  ["Tottenham", 73],
  ["Sunderland", 71],
  ["Man City", 65],
  ["Man United", 66],
  ["Liverpool", 64],
  ["Aston Villa", 58],
  ["Chelsea", 61],
  ["Crystal Palace", 354],
  ["Brentford", 402],
  ["Newcastle", 67],
  ["Brighton", 397],
  ["Everton", 62],
  ["Leeds United", 341],
  ["Burnley", 328],
  ["Fulham", 63],
  ["Nott'm Forest", 351],
  ["West Ham", 563],
  ["Wolves", 76],
  // Bundesliga
  ["Bayern Munich", 5],
  ["RB Leipzig", 721],
  ["VfB Stuttgart", 10],
  ["Dortmund", 4],
  ["Leverkusen", 3],
  ["Eintracht Frankfurt", 19],
  ["Hoffenheim", 2],
  ["FC Koln", 1],
  ["Werder Bremen", 12],
  ["Union Berlin", 28],
  ["SC Freiburg", 17],
  ["Wolfsburg", 11],
  ["Hamburger SV", 7],
  ["St Pauli", 20],
  ["Augsburg", 16],
  ["Mainz", 15],
  ["Heidenheim", 44],
  ["M'gladbach", 18],
  // Serie A
  ["Napoli", 113],
  ["Roma", 100],
  ["Milan", 98],
  ["Inter", 108],
  ["Bologna", 103],
  ["Como", 7397],
  ["Atalanta", 102],
  ["Juventus", 109],
  ["Udinese", 115],
  ["Lazio", 110],
  ["Cremonese", 457],
  ["Torino", 586],
  ["Sassuolo", 471],
  ["Cagliari", 104],
  ["Parma", 112],
  ["Lecce", 5890],
  ["Verona", 450],
  ["Fiorentina", 99],
  ["Pisa", 487],
  ["Genoa", 107],
  // Ligue 1
  ["PSG", 524],
  ["Lens", 546],
  ["Marseille", 516],
  ["Lyon", 523],
  ["Lille", 521],
  ["Monaco", 548],
  ["Strasbourg", 576],
  ["Nice", 522],
  ["Toulouse", 511],
  ["Rennes", 529],
  ["Paris FC", 1045],
  ["Brest", 512],
  ["Nantes", 543],
  ["Le Havre", 533],
  ["Angers", 532],
  ["Lorient", 525],
  ["Auxerre", 519],
  ["Metz", 545],
  // La Liga
  ["Real Madrid", 86],
  ["Barcelona", 81],
  ["Villarreal", 94],
  ["Espanyol", 80],
  ["Atletico Madrid", 78],
  ["Real Betis", 90],
  ["Rayo Vallecano", 87],
  ["Elche", 285],
  ["Athletic Club", 77],
  ["Getafe", 82],
  ["Sevilla", 559],
  ["Alaves", 263],
  ["Celta Vigo", 558],
  ["Osasuna", 79],
  ["Levante", 88],
  ["Mallorca", 89],
  ["Real Sociedad", 92],
  ["Valencia", 95],
  ["Oviedo", 1048],
  ["Girona", 298],
]);

// same but for api-football.com
export const team_to_id_new = new Map<string, number>([
  // Premier League
  ["Arsenal", 42],
  ["Bournemouth", 35],
  ["Tottenham", 47],
  ["Sunderland", 746],
  ["Man City", 50],
  ["Man United", 33],
  ["Liverpool", 40],
  ["Aston Villa", 66],
  ["Chelsea", 61],
  ["Crystal Palace", 52],
  ["Brentford", 55],
  ["Newcastle", 34],
  ["Brighton", 51],
  ["Everton", 62],
  ["Leeds United", 63],
  ["Burnley", 44],
  ["Fulham", 35],
  ["Nott'm Forest", 65],
  ["West Ham", 48],
  ["Wolves", 39],
  // Bundesliga
  ["Bayern Munich", 157],
  ["RB Leipzig", 173],
  ["VfB Stuttgart", 172],
  ["Dortmund", 165],
  ["Leverkusen", 168],
  ["Eintracht Frankfurt", 169],
  ["Hoffenheim", 167],
  ["FC Koln", 192],
  ["Werder Bremen", 162],
  ["Union Berlin", 182],
  ["SC Freiburg", 160],
  ["Wolfsburg", 161],
  ["Hamburger SV", 175],
  ["St Pauli", 186],
  ["Augsburg", 170],
  ["Mainz", 164],
  ["Heidenheim", 180],
  ["M'gladbach", 163],
  // Serie A
  ["Napoli", 492],
  ["Roma", 497],
  ["Milan", 489],
  ["Inter", 505],
  ["Bologna", 500],
  ["Como", 895],
  ["Atalanta", 499],
  ["Juventus", 496],
  ["Udinese", 494],
  ["Lazio", 487],
  ["Cremonese", 520],
  ["Torino", 503],
  ["Sassuolo", 488],
  ["Cagliari", 490],
  ["Parma", 523],
  ["Lecce", 867],
  ["Verona", 504],
  ["Fiorentina", 502],
  ["Pisa", 801],
  ["Genoa", 495],
  // Ligue 1
  ["PSG", 85],
  ["Lens", 116],
  ["Marseille", 81],
  ["Lyon", 80],
  ["Lille", 79],
  ["Monaco", 91],
  ["Strasbourg", 95],
  ["Nice", 84],
  ["Toulouse", 96],
  ["Rennes", 94],
  ["Paris FC", 114],
  ["Brest", 106],
  ["Nantes", 83],
  ["Le Havre", 111],
  ["Angers", 77],
  ["Lorient", 97],
  ["Auxerre", 108],
  ["Metz", 112],
  // La Liga
  ["Real Madrid", 541],
  ["Barcelona", 529],
  ["Villarreal", 533],
  ["Espanyol", 540],
  ["Atletico Madrid", 530],
  ["Real Betis", 543],
  ["Rayo Vallecano", 728],
  ["Elche", 797],
  ["Athletic Club", 531],
  ["Getafe", 546],
  ["Sevilla", 536],
  ["Alaves", 542],
  ["Celta Vigo", 538],
  ["Osasuna", 727],
  ["Levante", 539],
  ["Mallorca", 798],
  ["Real Sociedad", 548],
  ["Valencia", 532],
  ["Oviedo", 718],
  ["Girona", 547],
]);

export const skip_coaches = [
  "R. Lowe",
  "C. Wilder",
  "J. Tindall",
  "G. Potter",
  "A. Postecoglou",
  "S. Ireland",
  "G. Brazil",
  "V. Paunovic",
  "E. Sikora",
  "A. Hütter",
  "M. Debeve",
  "Z. Löw",
  "O. Werner",
  "D. Bauer",
  "J. Thorup",
  "M. Schmidt",
  "G. Seoane",
  "Sérgio Conceição",
  "I. Tudor",
  "L. Apolloni",
  "S. Morrone",
];

export const normalize_name = (name: string): string => {
  return exception_teams.get(name) ?? name;
};

export const map_team = (full_name: string): string => {
  return standings_map.get(full_name) ?? full_name;
};

export const map_team_name = (full_name: string): string => {
  return ODDS_MAP.get(full_name) ?? full_name;
};

export const toInt = (value: any): number | null => {
  const num = parseInt(value);
  return Number.isNaN(num) ? null : num;
};

export const get_team_to_id_new = (team: string): number => {
  return team_to_id_new.get(team) ?? -1;
};

export const curSeason = "2025";
export const urlSeason = "2526";
