-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "odds" (
	"bookmaker" text NOT NULL,
	"market_type" text DEFAULT 'h2h' NOT NULL,
	"odds_home" numeric,
	"odds_draw" numeric,
	"odds_away" numeric,
	"updated_at" timestamp DEFAULT now(),
	"match" bigint,
	CONSTRAINT "odds_bookmaker_match_unique" UNIQUE("bookmaker","match")
);
--> statement-breakpoint
ALTER TABLE "odds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teams" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_name" text NOT NULL,
	CONSTRAINT "teams_team_name_key1" UNIQUE("team_name")
);
--> statement-breakpoint
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "leagues" (
	"name" text PRIMARY KEY NOT NULL,
	"country" text,
	CONSTRAINT "leagues_name_key" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "leagues" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "players" (
	"name" text PRIMARY KEY NOT NULL,
	"image_url" text
);
--> statement-breakpoint
ALTER TABLE "players" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "upcomingMatches" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upcoming_matches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"MatchDate" text NOT NULL,
	"HomeTeam" text NOT NULL,
	"AwayTeam" text NOT NULL,
	"League" text NOT NULL,
	CONSTRAINT "upcoming_match_unique_idx" UNIQUE("MatchDate","HomeTeam","AwayTeam")
);
--> statement-breakpoint
ALTER TABLE "upcomingMatches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "matchStats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "match_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"HomeTeam" text NOT NULL,
	"AwayTeam" text NOT NULL,
	"MatchDate" text,
	"FTR" text,
	"HS" integer,
	"AS" integer,
	"HST" integer,
	"AST" integer,
	"HC" integer,
	"AC" integer,
	"FTHG" integer,
	"FTAG" integer,
	"HY" integer,
	"AY" integer,
	"HR" integer,
	"AR" integer,
	"HF" integer,
	"AF" integer,
	"League" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "matchStats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "standings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "standings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"league" text NOT NULL,
	"name" text NOT NULL,
	"season" text NOT NULL,
	"position" integer NOT NULL,
	"played" integer NOT NULL,
	"won" integer NOT NULL,
	"draw" integer NOT NULL,
	"lost" integer NOT NULL,
	"goalsAgainst" integer NOT NULL,
	"goalsFor" integer NOT NULL,
	"goalDifference" integer NOT NULL,
	"points" integer NOT NULL,
	"form" text,
	"recentGf" integer,
	"recentGa" integer,
	"type" text NOT NULL,
	CONSTRAINT "standings_name_season_type_unique" UNIQUE("name","season","type")
);
--> statement-breakpoint
ALTER TABLE "standings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "goalScorers" (
	"player" text NOT NULL,
	"goals" integer NOT NULL,
	"season" text NOT NULL,
	"team" text NOT NULL,
	"league" text,
	"imageUrl" text,
	CONSTRAINT "goalscorers_name_season_unique" UNIQUE("player","season")
);
--> statement-breakpoint
ALTER TABLE "goalScorers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "squad" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "squad_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"player" text,
	"position" text,
	"number" integer,
	"team" text,
	CONSTRAINT "squad_team_player_unique" UNIQUE("player","team")
);
--> statement-breakpoint
ALTER TABLE "squad" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "head2head" (
	"team1" text NOT NULL,
	"team2" text NOT NULL,
	"MP" integer DEFAULT 0,
	"team1_wins" integer DEFAULT 0,
	"team2_wins" integer DEFAULT 0,
	"draws" integer DEFAULT 0,
	"last5" integer[] DEFAULT '{RAY}' NOT NULL,
	CONSTRAINT "head_to_head_pkey" PRIMARY KEY("team1","team2"),
	CONSTRAINT "unique_teams" UNIQUE("team1","team2")
);
--> statement-breakpoint
ALTER TABLE "head2head" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "odds" ADD CONSTRAINT "odds_match_fkey" FOREIGN KEY ("match") REFERENCES "public"."upcomingMatches"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "upcomingMatches" ADD CONSTRAINT "upcoming_matches_AwayTeam_fkey" FOREIGN KEY ("AwayTeam") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "upcomingMatches" ADD CONSTRAINT "upcoming_matches_HomeTeam_fkey" FOREIGN KEY ("HomeTeam") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "upcomingMatches" ADD CONSTRAINT "upcoming_matches_League_fkey" FOREIGN KEY ("League") REFERENCES "public"."leagues"("name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "matchStats" ADD CONSTRAINT "match_stats_AwayTeam_fkey" FOREIGN KEY ("AwayTeam") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "matchStats" ADD CONSTRAINT "match_stats_HomeTeam_fkey" FOREIGN KEY ("HomeTeam") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "matchStats" ADD CONSTRAINT "match_stats_League_fkey" FOREIGN KEY ("League") REFERENCES "public"."leagues"("name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "standings" ADD CONSTRAINT "standings_league_fkey" FOREIGN KEY ("league") REFERENCES "public"."leagues"("name") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "standings" ADD CONSTRAINT "standings_name_fkey" FOREIGN KEY ("name") REFERENCES "public"."teams"("team_name") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "goalScorers" ADD CONSTRAINT "goalScorers_league_fkey" FOREIGN KEY ("league") REFERENCES "public"."leagues"("name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "goalScorers" ADD CONSTRAINT "goalScorers_player_fkey" FOREIGN KEY ("player") REFERENCES "public"."players"("name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "goalScorers" ADD CONSTRAINT "goalScorers_team_fkey" FOREIGN KEY ("team") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "squad" ADD CONSTRAINT "squad_player_fkey" FOREIGN KEY ("player") REFERENCES "public"."players"("name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "squad" ADD CONSTRAINT "squad_team_fkey" FOREIGN KEY ("team") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "head2head" ADD CONSTRAINT "head2head_team1_fkey" FOREIGN KEY ("team1") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "head2head" ADD CONSTRAINT "head2head_team2_fkey" FOREIGN KEY ("team2") REFERENCES "public"."teams"("team_name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "odds" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "odds" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "teams" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "teams" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "leagues" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "leagues" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Service role full write" ON "players" AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));--> statement-breakpoint
CREATE POLICY "Allow public read" ON "players" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "upcomingMatches" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "upcomingMatches" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "matchStats" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "matchStats" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "standings" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "standings" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Service role full write" ON "goalScorers" AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));--> statement-breakpoint
CREATE POLICY "Allow public read" ON "goalScorers" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "squad" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "squad" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Allow public read" ON "head2head" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Service role full write" ON "head2head" AS PERMISSIVE FOR ALL TO public;
*/